Fixed different types of bastions not breaking at the same time and added bastion health to damage messages
CivClassic/Bastion pull request #5
Opened 2019-08-17 02:34 UTC by xFier

2019-08-17 09:12 UTC, xFier commented
Removed the unexpectedly highly controversial health messages

2019-08-17 09:14 UTC, xFier commented
Opened the PR again

2019-08-18 19:12 UTC, Maxopoly requested changes

2019-08-18 19:12 UTC, Maxopoly commented on src/main/java/isaac/bastion/listeners/BastionDamageListener.java
> +		System.out.println(state.getMode().toString());
Remove this

2019-08-18 19:12 UTC, Maxopoly commented on src/main/java/isaac/bastion/listeners/BastionDamageListener.java
> +	private void damageRein(BlockPlaceEvent event)
This entire method is complete bogus, why are you copying Citadel code into Bastion

2020-05-02 01:05 UTC, Maxopoly commented
Not sure if this is still relevant, either way reopen the PR if you ever fix it

2020-05-02 01:05 UTC, closed without merging